version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - cats-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
    container_name: mfe-backend-api
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - cats-network

  mfe-shared:
    build: ./mfe-shared
    container_name: mfe-shared
    ports:
      - "8081:80"
    networks:
      - cats-network

  mfe-angular:
    build:
      context: .
      dockerfile: mfe-angular/Dockerfile
    container_name: mfe-angular
    ports:
      - "4200:80"
    depends_on:
      - mfe-shared
    networks:
      - cats-network

  mfe-react:
    build:
      context: .
      dockerfile: mfe-react/Dockerfile
    container_name: mfe-react
    ports:
      - "8080:80"
    depends_on:
      - mfe-shared
    networks:
      - cats-network

  root-config:
    build: ./root-config
    container_name: mfe-root-shell
    ports:
      - "9000:80"
    depends_on:
      - mfe-shared
      - mfe-react
      - mfe-angular
    networks:
      - cats-network

networks:
  cats-network:
    driver: bridge

volumes:
  mongo_data:
